### ISSUE TITLE
transfer to microformats for continued development

### ISSUE THREAD

**Issue by kartikprabhu** [microformats/mf2py#86]
There was some discussion of possibly moving this main mf2py repo to @microformats so that development of mf2py can continue.

cc: @kevinmarks @tantek @bear

**Comment by tommorris** [comment]
For various personal reasons, I'm far less active in open source and development these days, so I'd broadly welcome moving this project to the main @microformats organisation.

From my reading of [GitHub's documentation](https://help.github.com/articles/about-repository-transfers/), it doesn't look like it would break anything—issues and pull request URLs would be redirected.

Let's hold this open for a week in case anyone has any objections, but if nobody objects, I'll move the repository to the main @microformats organisation on or after 2018-02-28.

**Comment by kevinmarks** [comment]
You moving it so the issues would propagate was the goal, as if we fork it
there they get left behind.

On 20 Feb 2018 12:28, "Tom Morris" <notifications@github.com> wrote:

For various personal reasons, I'm far less active in open source and
development these days, so I'd broadly welcome moving this project to the
main @microformats <https://github.com/microformats> organisation.

From my reading of GitHub's documentation
<https://help.github.com/articles/about-repository-transfers/>, it doesn't
look like it would break anything—issues and pull request URLs would be
redirected.

Let's hold this open for a week in case anyone has any objections, but if
nobody objects, I'll move the repository to the main @microformats
<https://github.com/microformats> organisation on or after 2018-02-28.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tommorris/mf2py/issues/86#issuecomment-366962413>, or mute
the thread

**Comment by tommorris** [comment]
The repository has now been moved to its new home, the @microformats organisation.

**Comment by kartikprabhu** [comment]
thanks @tommorris
